services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql
