services:
  springboot-app:
    image: ayfood
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"