replicaCount: 2

image:
  repository: 941298098509.dkr.ecr.us-east-1.amazonaws.com/mazyfood
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

springBoot:
  activeProfile: postgresql

database:
  url: jdbc:postgresql://mazyfood-db.csdrtd9wr0vl.us-east-1.rds.amazonaws.com:5432/mazyfood
  username: mazyadmin
  password: mazyadmin
  driverClassName: org.postgresql.Driver

jpa:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  ddlAuto: update
  showSql: true

custom:
  persistence: postgresql
  paymentGateway: mock
